name: Triggered every 1hour
on:
  schedule:
    - cron:  '* */1 * * *'

jobs:
  setUpAndRun:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: "**/node_modules"
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Install Node.js dependencies
        run: |-
          if [[ "${{ steps.npm-cache.outputs.cache-hit }}" != "true" ]]; then
            npm install
          else
            echo "Using cache"
          fi
        working-directory: ./
      - name: Run Node.js script
        run: npm start
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }} 
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}